---
title: "Laktatprofil Løping"
format: html
editor: visual
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---



```{r load-data}
#| include: false
library(tidyverse)
library(readxl)
```

Reliability VO2

```{r}
#| echo: false

dat <- read_excel("data/rawdata.xlsx") %>%
  select(subject, timepoint, lac.4.vo2) %>%
  print()

dat %>%
  pivot_wider(names_from = timepoint, values_from = lac.4.vo2) %>%
  mutate(diff = post - pre) %>%
  summarise(s = sd(diff),
            m = mean(c(pre, post)),
            te = s / sqrt(2),
            cv = 100 * (te / m)) %>%
  print()
```

Reliability Speed

```{r}
dat <- read_excel("data/rawdata.xlsx") %>%
  select(subject, timepoint, lac.4.speed) %>%
  print()

dat %>%
  pivot_wider(names_from = timepoint, values_from = lac.4.speed) %>%
  mutate(diff = post - pre) %>%
  summarise(s = sd(diff),
            m = mean(c(pre, post)),
            te = s / sqrt(2),
            cv = 100 * (te / m)) %>%
  print()
```

Figure 1 - VO2

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-cap: "Figure text"

rawdata <- read_excel("data/rawdata.xlsx") %>%
  mutate(timepoint = factor(timepoint, 
                            levels = c("pre", "post"),
                            labels = c("Test", "Re-test")), 
         subject = factor(subject))

ggplot(data = rawdata, aes(x = timepoint, 
                                y = lac.4.vo2,
                           color = subject, 
                           group = subject)) +
  geom_point() +
  geom_line() +
  
  labs(x = "Timepoint", 
       y = "VO2 at 4 mmol/L [ml/min]", 
       title = "VO2 at 4 mmol/L",
       color = "Subjects")
```

Figure 2 - Speed

```{r}
library(ggplot2)
library(dplyr)
rawdata <- read_excel("data/rawdata.xlsx")
ggplot(data = rawdata, aes(x = timepoint, 
                                y = lac.4.speed,
                           color = subject)) +
  geom_point() +
   labs(x = "Timepoint", 
       y = "Speed at 4 mmol/L [ml/min]", 
       title = "Speed at 4 mmol/L",
       color = "Subjects")

```

Table Descriptives

```{r}
#| label: tbl-char
#| tbl-cap: "Group characteristics (at 4 mmol/L)"
#| warning: false
library(gt)
rawdata %>%
  select(subject, timepoint, lac.4.speed, lac.4.vo2) %>%
  group_by(timepoint) %>%
  summarise(gj1 = mean(lac.4.vo2, na.rm = TRUE),
            st1 = sd(lac.4.vo2, na.rm = TRUE),
            gj2 = mean(lac.4.speed, na.rm = TRUE),
            st2 = sd(lac.4.speed, na.rm = TRUE)) %>%
  mutate(timepoint = factor(timepoint, levels = c("pre", "post"),
                        labels = c("Pre",
                                   "Post"))) %>%
  gt(caption = md("Group characteristics")) %>%
  fmt_number(columns = gj1:st1:gj2:st2) %>%
  fmt_number(columns = gj1,
              decimals = 1) %>%
  fmt_number(columns = st1,
              decimals = 1) %>%
  fmt_number(columns = gj2,
              decimals = 1) %>%
  fmt_number(columns = st2,
              decimals = 1) %>%
  cols_label(timepoint = "Timepoint",
             gj1 = md("Mean VO<sub>2</sub><br><small>(mL/min)"),
             st1 = md("SD VO<sub>2</sub><br><small>(mL/min)"),
             gj2 = md("Mean Speed<br><small>(km/h)"),
             st2 = md("SD Speed<br><small>(km/h)"))
  
```

### 

Bibliography

[@hopkins2000]
